### ISSUE TITLE
libtinfo.so.5 missing on pop_OS, causes nitrogen 2.4.0 to fail

### ISSUE THREAD

**Issue by sfinnie** [nitrogen/nitrogen#116]
Hi Jesse, came across this installing on a stock Pop!_OS 20.10 machine with no-pre-existing Erlang installation.

Easily resolved (see below), raising in the hope it helps anyone else who has the same problem.

**How to re-create:**

1. Download [nitrogen 2.4.0 for linux on Cowboy](http://downloads.nitrogenproject.com.s3.amazonaws.com/2.4.0/linux/nitrogen-2.4.0-cowboy.tar.gz)
1. Unzip
1. run `bin/nitrogen start` as per [documentation](https://nitrogenproject.com/doc/index).

Result:

    /home/me/nitrogen/nitrogen/erts-11.1/bin/nodetool: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

**Fix:**

1. `sudo apt install libncurses5`
1. run `bin/nitrogen start`
1. check; open [localhost:8000](http://localhost:8000/) - loads OK.

-S.
 
--

EDIT: added call to start nitrogen after installing `libncurses5` & corrected spelling of `localhost`.

**Comment by choptastic** [comment]
Hey @sfinnie, Thanks for this heads up.  For now, I may leave this open like this for those googling the ncurses error.  And once the migration to rebar3 is complete, we'll see if this error continues as is, or if it self-resolves.

Otherwise, I may look into a proper ncurses existence check and alert the user if it's missing.

**Comment by sfinnie** [comment]
@choptastic makes sense, no problem. Thx for response.
