### ISSUE TITLE
erlang module doesn't map to url gives 404

### ISSUE THREAD

**Issue by noargs** [nitrogen/nitrogen#117]
Hi There,
i created a module **visitors_admin.erl** in site > src directory and it doesnt map to **localhost:8000/visitors/admin** whereas **index.erl** > **localhost:8000** works fine

- i have double checked the spellings of both **module name** and **endpoint**
- i also used sync:go().  in case if it doesnt recompile but my site>ebin does contain visitors_admin.beam file
- i also restarted the shell by stopping q(). and running bin/nitrogen console but still getting 404 on visitors/admin endpoint

kind regards

**Comment by choptastic** [comment]
Hi @noargs,

That's very interesting.

From the erlang shell, if you run `visitors_admin:module_info()`, what do you get?

-Jesse

**Comment by choptastic** [comment]
As a follow-up.  Try this:

After stopping the VM with `q()`

Run `make` at the shell, then restart the VM with `bin/nitrogen console`

Then check if the address is working.

If that's still not working, feel free to zip up the whole nitroboard project directory and send it to me and I'll give it a test run on my local machine to see if I can reproduce it.

**Comment by noargs** [comment]
wow you are in my book too lol 

**heres the visitors_admin:module_info() instruction in erlang shell**

```
[{module,visitors_admin},
 {exports,[{module_info,0},{module_info,1}]},
 {attributes,[{vsn,[319369965591564883774613138258261628972]},
              {author,"azzi"}]},
 {compile,[{version,"7.6.5"},
           {options,[debug_info,fail_on_warning,
                     {i,"/Users/azzi/erlang_w/build_with_nitrogen/nb/site/include"},
                     {type,erl}]},
           {source,"/Users/azzi/erlang_w/build_with_nitrogen/nb/site/src/visitors_admin.erl"},
           {outdir,"/Users/azzi/erlang_w/build_with_nitrogen/nb/site/ebin"},
           {i,"/Users/azzi/erlang_w/build_with_nitrogen/nb/site/include"}]},
 {native,false},
 {md5,<<240,68,107,2,130,238,3,24,139,52,221,41,216,26,
        216,44>>}]
```

**Here's the make instruction you said**

Compiling /Users/azzi/erlang_w/build_with_nitrogen/nb/site/src/visitors_admin.erl failed:
ERROR: compile failed while processing /Users/azzi/erlang_w/build_with_nitrogen/nb/site: rebar_abort
make: *** [Makefile:12: compile] Error 1

**Comment by noargs** [comment]
as per last instruction i have sent it to your email with subject **my nitro project Reference > Github issue on nitrogen repo #117** thanks for your time

**Comment by choptastic** [comment]
Hi @noargs!

Thanks for sending the files.

The problem is that the visitors_admin.erl file has a number of errors:

When I run `make`, I get this:

```
Compiled src/visitors_db.erl
Compiled src/nitrogen_app.erl
Compiled src/nitrogen_sup.erl
/home/gumm/code/nb/site/src/visitors_admin.erl:46: syntax error before: '='
/home/gumm/code/nb/site/src/visitors_admin.erl:55: syntax error before: '{'
/home/gumm/code/nb/site/src/visitors_admin.erl:13: function inner_body/0 undefined
/home/gumm/code/nb/site/src/visitors_admin.erl:87: function inner_body/0 undefined
/home/gumm/code/nb/site/src/visitors_admin.erl:93: function parse_date/1 undefined
/home/gumm/code/nb/site/src/visitors_admin.erl:75: Warning: variable 'Done' is unused
Compiling /home/gumm/code/nb/site/src/visitors_admin.erl failed:
ERROR: compile failed while processing /home/gumm/code/nb/site: rebar_abort
```
Addressing these syntax errors in order:

Line 46: `#textbox={ id=company },` 

This should just be `#textbox{id=company},`

Line 55: `[time_option{H,0,0} || H <- Hours]}.`

This should be `[time_option({H,0,0}) || H <- Hours]}.` (it's missing the parentheses around the {H,0,0}

Line 75: `event(Done) ->`

This should be `event(done) ->` - The uppercase `Done` is a variable, while `done` (lowercase) is an atom.

Finally, Line 93: `Date = parse_date(wf:q(date1)),` This line is actually fine, but it's saying `parse_date` is not defined.  That's because on line 69, you have a typo where you've defined it as `parse_data` (rather then `parse_date`).

If you fix those, it should compile and work.  When you run `make` you're not seeing the error messages I posted above?

**Comment by choptastic** [comment]
BTW, I skipped the errors calling `inner_body/0` because once the syntax error in `inner_body/0` is fixed, the errors will go away on their own.

**Comment by noargs** [comment]
Hi @choptastic  

that was some silly mistakes i did. i will remember this process to debug my app in future. thank you very much, problem is solved

**Comment by choptastic** [comment]
Wonderful! I'm so glad that fixed it.

Yeah, just be on the lookout for those syntax errors, and you should be good to go. But if you encounter more, feel free to ask. Lloyd and I certainly want you to ask the questions instead of getting frustrated.

Thanks again for asking, and we appreciate you buying our book :)
