### ISSUE TITLE
Conceptulizing REST handlers

### ISSUE THREAD

**Issue by th31nitiate** [nitrogen/nitrogen#136]
I would like to better understand rest handlers and the like. 

The concept I have is pretty straight forward, though I love HTML server side rendering provided by nitrogen. I would like to also expose an API for accessibility by none HTML speaking interfaces. For reliability reasons I would like to have a java script type UI that can be hosted on various storage buckets and with a CDN, thus if there is networking issues the JS like thing can instruct the user regarding what to do, for the type of environment I am referencing it's much simpler to create a local area shared cache encase of geological outage's as opposed to hosted servers.  

The issue is that I seen the rest behavior which I have managed to test but it does seem to be functioning as  expected. I get error for missing function HTTP method which I add. Though I am not get the response I required just get `undef` unless I forgot to take the path info argument (though I doubt this I will double check). I  have not had the chance to look in the code to find out what's happening. It would be quicker to ask in my view.

I seen the rest_form which seems to be a file since for example it might be possible to have nitrogen render the form's and for the generated rest_form to be presented to the user through the user interface. Though I don't know if that's plausible with the up rise of virtual DOM's.

Here are the main questions:

1. You mention cowboy and web-machine which seem really cool and stable, though I want the core logic to remain within nitrogen (I feel more comfortable developing with it). How would I possibly connect these to it for example Cowboy ?

I get that each time we visit a page it loads main and then when main runs it can load a template that can then call a function to generate HTML as needed. In REST's case it would be JSON, though again I have no way of bridging the gap between an external REST handler & nitrogen provided functions.

2. How do I use the nitrogen rest handler correctly ?

Is this simply adding the rest handler behavior then once done we can  add `get(PathInfo)` then start processing messages via JSON encoding and decoding.

I cant seem to see the demo available on the demos page regarding the REST handler. If I can grasp the concept I will try see if I can make a pull request to add the demo code. 

One more question

3. Is there a web-socket interface within nitrogen that we can access. I cant seem to see anything in the documentation ?

**Comment by choptastic** [comment]
This is a great question!

It does look like the rest handler demo was never built, so that certainly limits that.

For the `undef` message you're getting, I'm not sure I can answer that without more context.

1. The webmachine or cowboy distinction doesn't really apply here, as you mentioned, since you want your app to use nitrogen's rendering, so just using a nitrogen rest handler is enough.

2. The documentation for the rest handler is here (which I believe you've already found): https://nitrogenproject.com/doc/rest.md

The short of it is that it works almost exactly like a normal page module, except instead of `main()` being your entry point, you have a number of entry points, like `get("some_endpoint")` or `post("some_other_endpoint")`

The other major difference is that the return value is either a `Body` as is typical of the return from `main()` or a `{StatusCode, Body}` tuple, like `{403, "You're not allowed to see this"}`.

Mimicking this, you could either replace your page's `main()` with `get("") ->` which would be the effective replacement of main, then the other clauses for `get(X)` could be the JSON return values you want retrieved, or you could split the REST page into its own module (probably, the way I'd go in this scenario).

There is a way to overload the websocket interface with the latest version from the `rebar3` branch.  How to do this is here:

https://github.com/nitrogen/NitrogenProject.com/blob/rebar3/src/demos/demos_websocket.erl

**Comment by th31nitiate** [comment]
I have managed to test it out and again. I seem to be getting the same issues. It seems the problem is even if the behavior is imported it still continues to look for the main function.

```
{error,first_request,
    {url,"localhost:8000/"},
    {error,undef,
        [{index,main,[],[]},
         {wf_core,run_first_request,0,[{file,"src/wf_core.erl"},{line,228}]},
         {wf_core,run_catched,0,[{file,"src/wf_core.erl"},{line,90}]},
         {wf_core,run,0,[{file,"src/wf_core.erl"},{line,23}]},
         {cowboy_simple_bridge_anchor,init,2,
             [{file,
                  "src/cowboy_bridge_modules/cowboy_simple_bridge_anchor.erl"},
              {line,36}]},
         {cowboy_handler,execute,2,
             [{file,"src/cowboy_handler.erl"},{line,41}]},
         {cowboy_stream_h,execute,3,
             [{file,"src/cowboy_stream_h.erl"},{line,320}]},
         {cowboy_stream_h,request_process,3,
             [{file,"src/cowboy_stream_h.erl"},{line,302}]}]}}
```

I can maybe hack around it by using a case statement and the pathinfo data provided by `wf:path_info` to match based on the request method though that seems like a hack. 

Oooh and I just figured it out. The index page is resolved souly for the HTML based function. I had to create a completely separate `.erl` then after that the `curl -X <method> http://localhost:8000/api` requests were successful.

As for the rebar3 branch all seems good it works with latest version of erlang which is delight. Though every time I compile I error with error code 2.

```
make[2]: don't know how to make w. Stop

make[2]: stopped in /usr/home/th31nitiate/Code/testerlng/myapp
gmake[1]: *** [Makefile:245: slim] Error 2
gmake[1]: Leaving directory '/usr/home/th31nitiate/Code/testerlng/nitrogen'
gmake: *** [Makefile:105: slim_cowboy] Error 2
```

The application still works fine in terms of the index page but the JS callbacks aren't really working. The index clickme button I get the following error:

![erlangerr](https://github.com/nitrogen/nitrogen/assets/14749635/2e2857cd-bd73-4e0a-90fc-360f7958ab8a)


I noticed by looking at the makefile `@(./update_config_to_rebar3.escript rebar.config fix_relx_apps)` this file was missing in the application folder `update_config_to_rebar3.escript` so I added it to be copied over  `+{file, "common/update_config_to_rebar3.escript", "{{prefix}}/{{name}}/update_config_to_rebar3.escript"}.`. This don't seem to fix the problem but I imagine the error must be happening there.

I checked the escript briefly and the fix_relx_apps does not seem to be a command or function. It could be that not too sure if you can elaborate on its purpose ?

**Comment by choptastic** [comment]
For the easier answer, `update_config_to_rebar3.escript` script is the last part of the "upgrade from Nitrogen 2 to Nitrogen 3" process. It is *supposed* to download when you do the conversion from 2 to 3, the it should end with "look over your rebar.config and if it looks good, run the `make fix-deps`, which is supposed to run that script.

All *that* script does is looks at the newly downloaded deps, and updates rebar.config to include those libraries in the relx apps list.

However, that still doesn't answer your questions about why postbacks aren't working in a REST handler.  And the error is in bert.js, that at least tells us that bert.js and nitrogen.js are both loading, so that's good.

**Comment by choptastic** [comment]
To do a little more testing, I do believe this error has something to do with the upgrade from N2 to N3.

I did a little testing on stock N3 from here, and this worked as expected with postbacks:

https://pastebin.com/pW9VYdh0
