### ISSUE TITLE
meaning of FastMap error

### ISSUE THREAD

**Issue by th31nitiate** [nitrogen/nitrogen#144]
Again I love this project it seems very intuitive & for the most it always has the needed functionality while begin easily extendable through the creation of custom elements. if anything is wrong it's not so difficult to debug and find the solution. Just wanted to say thanks again, I appriciate it.

Anyway I keep seeing this error, though not multiple times on a single running instance but it seems to show up after starting an application and after that I tend to not see it again. 

```
Nitrogen Global FastMap: Building wf_fastmap_worker with this config:
#{default_grid_system => grid960,
  default_grid_system_module => element_grid_960,
  {grid_system,grid960} => element_grid_960}

(If you see this more than a few times per day,
 you're probably updating this too much)
```

I was wondering if you could help shed some light as to its meaning ?

When it comes to generating HTML for nitrogen elements do we have to be concerned about how many elements we use when generating a page ?

**Comment by choptastic** [comment]
Hey, sorry for missing this post.  It's not actually an error.   I build a quick lookup system (called [`wf_fastmap`](https://github.com/nitrogen/nitrogen_core/blob/master/src/lib/wf_fastmap.erl)) similar to mochiglobal and/or persistent_term.   The point of it was to add a grid system "handlers" (so to speak), that can be looked up at the speed of an atom, so it relies exclusively on pattern matching, compiles a new module every time something changes, and since it's overkill to build out that whole system just for a currently expreimental system, I wanted to see a notice when it recompiles.

So nothing to worry about here.  This notice will likely eventually go away, but for now, it's just making sure it's not aggresively rebuilding this module.

**Comment by th31nitiate** [comment]
thanks I appreciate your response. It was just something I thought I would double check since it was my first time seeing this message. 

The code seems pretty well documented, so next I will make sure to search the code base first before asking a question.
