### ISSUE TITLE
Unable to upload files while using conversejs

### ISSUE THREAD

**Issue by prabhakarbca** [nitrogen/nitrogen#87]
I am using coversejs for chats in my nitrogen application. While using coversejs in my template, #upload{} is not working. It triggers upload start event and failed to upload the file. After removing the conversejs everything seems working fine. What needs to be done to work with conversejs?

**Comment by choptastic** [comment]
Some light googling around turned up what I suspect is at fault here:

https://github.com/jcbrand/converse.js/issues/69

I'd probably first try putting the converse.js reference in your template
*above* the rest of the scripts (above nitrogen and js).  Or, possibly
better, would be to use a minified version without jquery built in (because
no need to have two jqueries, and they should be compatible).

I hope that helps a bit,

-Jesse

On Sat, Mar 28, 2015 at 10:38 AM, prabhakarbca <notifications@github.com>
wrote:

> I am using coversejs for chats in my nitrogen application. While using
> coversejs in my template, #upload{} is not working. It triggers upload
> start event and failed to upload the file. After removing the conversejs
> everything seems working fine. What needs to be done to work with
> conversejs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nitrogen/nitrogen/issues/87>.
>



-- 
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by prabhakarbca** [comment]
Thanks for the suggestion. Actually I replaced the converse.min.js (converse/builds/converse.min.js) with converse.js (converse/converse.js). This solved my issue. Thanks once again.

**Comment by choptastic** [comment]
Excellent!

Glad to hear it!

On Tue, Mar 31, 2015 at 1:06 AM, prabhakarbca <notifications@github.com>
wrote:

> Thanks for the suggestion. Actually I replaced the converse.min.js
> (converse/builds/converse.min.js) with converse.js (converse/converse.js).
> This solved my issue. Thanks once again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nitrogen/nitrogen/issues/87#issuecomment-87953434>.
>



-- 
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm
