### ISSUE TITLE
Attempt to use embed fails

### ISSUE THREAD

**Issue by sschaefer** [nitrogen/nitrogen#90]
I'm having trouble with embed, at commit 96077092800b9c4145d450fed7abb0bc0cf39621

Note the failure to compile index.erl and to copy files into lib/nitrogen_core/www

I presume there are some prerequisites I failed to satisfy.  What are those?

[sps@corydon visiweave-0.1.0]$ /home/sps/Git/nitrogen/embed

---

***\*           NITROGEN WEB FRAMEWORK EMBEDDER            ****

---

***\*   Adding Nitrogen to an existing Erlang Application  ****

---

---

NOTE: BEFORE PROCEEDING IT'S HIGHLY RECOMMENDED THAT YOU MAKE
      NEW BRANCH IN YOUR SOURCE CODE MANAGEMENT SYSTEM, OR AT
      LEAST MAKE A BACKUP OF YOUR DIRECTORY, AS THIS WILL MAKE
      CHANGES TO THE CURRENT DIRECTORY TREE BY ADDING AND
      MODIFYING FILES.

Will be installing from '/home/sps/Git/nitrogen' into '/home/sps/Git/visiweave-0.1.0'

Web server to use?
Options are (c)owboy, (i)nets, (m)ochiweb, (w)ebmachine, (y)aws.
Please choose (i/m/c/w/y): c
Where to put the Erlang code for Nitrogen pages and initialization [Default: src/nitrogen/]: 
Where to put the Erlang headers [Default: include/]: 
Where to put the static directory (for js, css, etc) [Default: priv/static/]: 
Where to put the templates directory [Default: priv/templates/]: 
Where to put the config files [Default: etc/]: 
Install the plugin scripts and configs? (y/n): y
Add Nitrogen dependencies to rebar.config automatically? (nitrogen_core, simple_bridge, nprocreg, sync, cowboy, and any of cowboy's dependencies. (y/n): y
Add a 'make plugins' rule to the Makefile? (y/n): y
Add a 'make copy-static' rule to the Makefile? (y/n): y
Run 'make' after installation? (y/n): y

---

**\* We're almost ready to go. Please review: 
**\* Erlang Source: src/nitrogen/
**\* Erlang Headers: include/
**\* Static Resources: priv/static/
**\* Nitrogen Templates: priv/templates/
**\* Config Files: etc/
**\* Install Plugin Script: Yes
**\* Add 'make plugins' rule to Makefile: Yes
**\* Add 'make copy-static' rule to Makefile: Yes
**\* Add dependencies to rebar.config: Yes
**\* Run 'make' after all is complete: Yes

---

Are you sure you want to proceed? (y/n): y
Setting 'backend' in simple_bridge.config to 'cowboy'
Fixing Template paths in /home/sps/Git/visiweave-0.1.0/src/nitrogen/actions
Fixing Template paths in /home/sps/Git/visiweave-0.1.0/src/nitrogen/elements
Fixing Template paths in /home/sps/Git/visiweave-0.1.0/src/nitrogen/index.erl
Fixing Template paths in /home/sps/Git/visiweave-0.1.0/src/nitrogen/mobile.erl
Fixing Template paths in /home/sps/Git/visiweave-0.1.0/src/nitrogen/nitrogen_main_handler.erl
Fixing Template paths in /home/sps/Git/visiweave-0.1.0/src/nitrogen/nitrogen_sup.erl
Fixing Static paths in /home/sps/Git/visiweave-0.1.0/etc//app.config
Fixing Static paths in /home/sps/Git/visiweave-0.1.0/etc//simple_bridge.config
Fixing Static paths in /home/sps/Git/visiweave-0.1.0/etc//sync.config
Fixing static and include paths in /home/sps/Git/visiweave-0.1.0/plugins.config
Merging Nitrogen and cowboy dependencies
Generating "/home/sps/Git/nitrogen/rel/overlay/rebar.config"
Adding deps from "/home/sps/Git/nitrogen/rel/overlay/rebar.config" into "/home/sps/Git/visiweave-0.1.0/rebar.config"
Adding 'make plugins' to Makefile
Adding 'make copy-static' rule to Makefile
 ERLC   visiweave_nodes.erl visiweave_sup.erl visiweave_data_tests.erl index.erl mobile.erl nitrogen_main_handler.erl nitrogen_sup.erl visiweave_app.erl visiweave_roots.erl visiweave_data.erl
src/nitrogen/index.erl:4: can't find include lib "nitrogen_core/include/wf.hrl"
src/nitrogen/index.erl:6: record template undefined
src/nitrogen/index.erl:11: record container_12 undefined
src/nitrogen/index.erl:17: record h1 undefined
src/nitrogen/index.erl:18: record p undefined
src/nitrogen/index.erl:23: record p undefined
src/nitrogen/index.erl:24: record button undefined
src/nitrogen/index.erl:25: record p undefined
src/nitrogen/index.erl:29: record p undefined
src/nitrogen/index.erl:31: record link undefined
src/nitrogen/index.erl:36: record panel undefined
src/nitrogen/index.erl:3: export_all flag enabled - all functions will be exported
make: **\* [ebin/visiweave.app] Error 1
cp: cannot stat ‘lib/nitrogen_core/www/_’: No such file or directory
make: *_\* [copy-static] Error 1

---

***\*                          Installation Complete                        ****

---

There are a few manual steps you must take before you're completely set up:

1) You must make sure to start Nitrogen.  The easiest way is by
    adding `nitrogen_sup:start_link()` to your application.

2) You must make sure that the config files in etc/ are properly
   loaded. This can be done with a vm.args file if you're using a reltool
   generated release, or it can be done by adding additional -config calls to
   the commandline call that launches your app.

3) You may need to add the new packages (nitrogen_core, simple_bridge,
   nprocreg, etc) to your app's code path (the easy way is with the -pa flag
   in the `erl` call.)

Congratulations on adding Nitrogen to your Application

**Comment by choptastic** [comment]
Hmm. interesting, looks like I'm making some assumptions that aren't always true (I guess I didn't think about it).

The embed script assumes you use rebar to build your app, and as such, adds dependencies to rebar.config.  If, however, your app doesn't actually run rebar, you'll need to retrieve the necessary dependencies (assuming you're using erlang.mk or just raw compiling with erlc).

The assumption that nitrogen makes is that `make` will run `./rebar get-deps` and `./rebar compile`  If the dependencies aren't gotten, then the `nitrogen_core` library will be missing, hence the errors for the missing record definitions.

**Comment by sschaefer** [comment]
Thanks; I've been using erlang.mk without any serious investment in it.  I'll go learn rebar now, and I doubt many of your users would object to that requirement.

**Comment by sschaefer** [comment]
I adopted rebar, and got to the point where I could run "./rel/visiweave/bin/visiweave console" after a "rebar generate", as well as "rebar compile eunit" with all tests passing.  (There was an ugly need to edit rel/reltool.config to find my dependencies.) I then ran ../nitrogen/embed and got the same errors.

If this is still a rebar problem, do you have a minimal example rebar.config that works?  I don't feel like I've "learned" rebar yet.

**Comment by choptastic** [comment]
Thanks for the followup. Based on this that you're generating a release and then trying to run the embed, my suspicion is that you'd be better off manually integrating Nitrogen with your project, or rather running `embed` *before* running the `generate` (making it a dependency prior to generating the release).

The embed script is mostly for taking a pretty standard Erlang application and adding Nitrogen to it, rather than adding Nitrogen to a *release*, which is a slightly different beast.

The `embed` script really just does a handful of simple things:

* Adds dependencies for nitrogen_core, simple_bridge, nprocreg, sync, and the desired server (yaws,cowboy, etc) https://github.com/nitrogen/nitrogen/blob/master/embed#L136-L140
* Copy config files from the standard package (https://github.com/nitrogen/nitrogen/blob/master/embed#L113-L114)
* Copy necessary Erlang, Header, Template files, and web static resources (https://github.com/nitrogen/nitrogen/blob/master/embed#L116-L135)
* Modify the makefile to add `make plugin` https://github.com/nitrogen/nitrogen/blob/master/embed#L171-L177

Overall, it's relatively simple, but I haven't tried running it in an already generated release.

So I'd try running it before generating your release, then make sure all is well with your reltool or relx config files (such that all dependencies are properly listed), then seeing what happens after running generate.

If all else fails, if you're willing to share your project with me (privately, I'd assume), if you want to give me read access to the repo so I can attempt to clone and test locally (or if you just wanted to archive it up and email me a dropbox link or something, that works too).

As a practical example of using embed, these instructions are a *little* out of date, but I wrote this up when I initially made the script: http://sigma-star.com/blog/post/embedding-nitrogen

**Comment by choptastic** [comment]
Hi @sschaefer, just checking in to see if you ever got this working? I know it's been half a year.
