### ISSUE TITLE
app name in config should be changed to nitrogen_core

### ISSUE THREAD

**Issue by choptastic** [nitrogen/nitrogen#98]
Currently, it's set to `nitrogen`, which works fine for the default build process, but if your application isn't named `nitrogen`, you need a custom handler.  Changing the config to `nitrogen_core` will ensure that the app name doesn't matter.

Try to read the app `nitrogen` also, as a fallback for backwards compatibility with folks using the default config.

**Comment by erlanger** [comment]
I would suggest to have an architectural change to make nitrogen follow the same pattern as any other erlang application.

1. Separate all nitrogen code/directory structure from the user application- call this application nitrogen
2. Make it so that all the user application needs to do is to include the nitrogen application in its rebar deps configuration
    2.1 all the necessary work happens within the *nitrogen* rebar.config file, using 
         pre_hooks and post_hooks as necessary - this is so that it works properly as a rebar
         dependency, without the user having to do anything different than is done with other dependencies

This will make it much easier to develop new apps with nitrogen.

**Comment by choptastic** [comment]
Thank you. Good ideas, and something of this nature will be done for Nitrogen 3 and the conversion to rebar3/relx. After I finish the 2.4 release, I'll begin the transition to rebar3 for Nitrogen 3.

**Comment by erlanger** [comment]
That is great, I look forward to it.
